spring:
  profiles:
    active:
      - test:
---
spring:
  profiles: dev #开发环境
  application:
    name: microservice-config-bigdata-dev
---
spring:
  profiles: test #测试环境
  application:
    name: microservice-config-bigdata-test
#请保存为UTF-8格式